#!/bin/bash
# Regenerates shaders_spv.h from the GLSL sources (needs glslangValidator).
set -e
cd "$(dirname "$0")"
out=../shaders_spv.h
{
  echo "// Generated by shaders/build.sh from fullscreen.vert and planar_csc.frag. Do not edit."
  echo "#pragma once"
  echo "#include <cstdint>"
  for s in fullscreen.vert planar_csc.frag; do
    name=$(echo "$s" | tr '.' '_')
    glslangValidator -V --quiet "$s" -o "/tmp/$name.spv"
    echo "static const uint32_t ${name}_spv[] = {"
    od -An -v -t x4 -w16 "/tmp/$name.spv" | sed 's/ \([0-9a-f]\{8\}\)/ 0x\1,/g'
    echo "};"
  done
} > "$out"
